sudo:required
services:
  - docker

before_install:
  - docker build -t senthil326/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true senthil326/docker-react npm run test -- --coverage